server:
  port: 8080

spring:
  application:
    name: collector-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/collector}
    username: ${SPRING_DATASOURCE_USERNAME:collector}
    password: ${SPRING_DATASOURCE_PASSWORD:collector}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8180/realms/collector}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/collector/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus