server:
  port: 8080

spring:
  application:
    name: collector-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/collector
    username: collector
    password: collector
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/collector
          jwk-set-uri: http://localhost:8180/realms/collector/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus